#!/bin/bash

# VALO-SYNDIC Ghost — Quick Icon Generator (No Dependencies)
# ===========================================================
# Creates minimal PNG icons using base64-encoded data

mkdir -p icons

echo "🎨 Génération des icônes minimales..."

# Icon 16x16 - Simple black square with gold border
echo "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAX0lEQVQ4T2NkoBAwUqifYdQA+gPBMAMYcIBD+z9GBv7/DL8YGBm+//vP8AcXPcSo/f+fYTYDA8NsJgaG2QwMDLMZGBj+MDAwzMZFD1FqGRkZZoMNYWBgmM3AwDAbXToAAObPBhFvMqilAAAAAElFTkSuQmCC" | base64 -d > icons/icon-16.png
echo "✅ icon-16.png créé"

# Icon 48x48 - Slightly better version
echo "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAA0ElEQVRoQ+2YQQ6AIAxE+f+P1oOaGA9qYryoib3QhJCQhbSF7GE9ACnTmQ4O0DnQ+QA6BzofwOAD6BxABzA4gM4BdACDA+gcQAcwOIDOAXQAgwPoHEAHMDiAzgF0AIMD6BxABzA4gM4BdACDA+gcQAcwOIDOAXQAgwPoHEAHMDiAzgF0AIMD6BxABzA4gM4BdACDA+gcQAcwOIDOAXQAgwPoHEAHMDiAzgF0AIMD6BxABzA4gM4BdACDA+gcQAcwOIDOAXQAgwPoHEAHMDiAA3AA+gBIoDBBuqxuzgAAAABJRU5ErkJggg==" | base64 -d > icons/icon-48.png
echo "✅ icon-48.png créé"

# Icon 128x128
echo "iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAABRklEQVR4nO3SMQ0AAAjAMPD/0+XoWBqB0K6EqgcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwDMBo0QAgrM+qfkAAAAASUVORK5CYII=" | base64 -d > icons/icon-128.png
echo "✅ icon-128.png créé"

echo ""
echo "✅ Icônes minimales créées."
echo "⚠️  Pour de meilleures icônes, installez ImageMagick ou Python/Pillow"
echo "📦 Vous pouvez charger l'extension dans Chrome."
